export const constants = {
    CONNECT_WALLET: "CONNECT_WALLET",
    CHANGE_ACCOUNT: "CHANGE_ACCOUNT",
    CHANGE_CHAIN: "CHANGE_CHAIN",
    INIT_TOKENS_CONTRACTS: "INIT_TOKENS_CONTRACTS",
    UPDATE_LIQUIDITY_INFO: "UPDATE_LIQUIDITY_INFO",
    SELECTED_TOKEN_1: "SELECTED_TOKEN_1",
    SELECTED_TOKEN_2: "SELECTED_TOKEN_2",
    SWAP_PERFORMED: "SWAP_PERFORMED",
};
