export const actionConstants = {
    CONNECT_WALLET: "CONNECT_WALLET",
    CHANGE_ACCOUNT: "CHANGE_ACCOUNT",
    CHANGE_CHAIN: "CHANGE_CHAIN",
    INIT_TOKENS_CONTRACTS: "INIT_TOKENS_CONTRACTS",
    UPDATE_LIQUIDITY_INFO: "UPDATE_LIQUIDITY_INFO",
    UPDATE_TOKEN_BALANCE: "UPDATE_TOKEN_BALANCE",
    LIQUIDITY_UPDATE_PERFORMED: "LIQUIDITY_UPDATE_PERFORMED",
};
